" Spelling fixes
inoreabbrev stephanie Stephanie
inoreabbrev sTehpnaie Stephanie
inoreabbrev sTepahnie Stephanie
inoreabbrev sTephanie Stephanie
inoreabbrev setphanie Stephanie
inoreabbrev stehpnaie Stephanie
inoreabbrev stepahnie Stephanie
inoreabbrev stephaien Stephanie
inoreabbrev stephaine Stephanie
inoreabbrev stephnaie Stephanie
inoreabbrev STehpnaie Stephanie
inoreabbrev STepahnie Stephanie
inoreabbrev STephanie Stephanie
inoreabbrev Setphanie Stephanie
inoreabbrev Stehpnaie Stephanie
inoreabbrev Stepahnie Stephanie
inoreabbrev Stephaien Stephanie
inoreabbrev Stephaine Stephanie
inoreabbrev Stephnaie Stephanie
inoreabbrev molly Molly
inoreabbrev susie Susie
inoreabbrev frankie Frankie
inoreabbrev adn and
inoreabbrev nad and
inoreabbrev abck back
inoreabbrev fo of
inoreabbrev goig going
inoreabbrev gonig going
inoreabbrev hte the
inoreabbrev insetad instead
inoreabbrev laong along
inoreabbrev ot to
inoreabbrev taht that
inoreabbrev teh the
inoreabbrev tehy they
inoreabbrev thinsg things
inoreabbrev wiht with
inoreabbrev yestardy yesterday
inoreabbrev yesterady yesterday
inoreabbrev yoru your
